// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190617221705_commentdislike")]
    partial class commentdislike
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            Body = "Aut alias et consequatur nisi eum debitis.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(2100),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(2993)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 11,
                            Body = "Aperiam asperiores sint ut aspernatur eum odit.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4024),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4037)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 20,
                            Body = "Natus aliquam vel omnis occaecati vitae quisquam.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4286),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4295)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 11,
                            Body = "Accusamus perferendis maxime quisquam porro ad placeat.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4371),
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4375)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            Body = "Ipsam eius id autem laudantium.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4437),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4442)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            Body = "Ipsam qui fugit ut dignissimos.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4526),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4535)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Body = "Fuga dicta corrupti quaerat aut rerum vero et impedit.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4611),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4615)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 13,
                            Body = "Et dolorem quidem officia ut harum labore laboriosam et.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4775),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4784)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 10,
                            Body = "Omnis nihil laborum id.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4846),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4851)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Omnis soluta delectus est distinctio accusantium a.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4917),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4922)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 14,
                            Body = "Maiores dicta ducimus quae minus.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4980),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(4984)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 15,
                            Body = "Cupiditate ad vel tenetur.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5042),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5046)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Omnis voluptatem impedit.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5091),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5095)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 15,
                            Body = "Sequi vel ducimus.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5144),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5148)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 11,
                            Body = "Quia aut natus nemo iusto accusamus voluptatibus libero.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5268),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5273)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 20,
                            Body = "Illum possimus quia omnis.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5331),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5335)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "Animi reiciendis et laborum aut omnis magnam excepturi eaque.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5415),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5420)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            Body = "Repellat nisi et alias ipsam non sapiente delectus.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5491),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5495)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            Body = "Et ut repudiandae dicta necessitatibus molestiae non sunt.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5562),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5566)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 18,
                            Body = "Aspernatur eos et error sunt et inventore et.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5695),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 171, DateTimeKind.Local).AddTicks(5704)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(7669),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(8696),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9651),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9665),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9709),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9718),
                            UserId = 15
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9749),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9753),
                            UserId = 10
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9780),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9789),
                            UserId = 13
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9816),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9820),
                            UserId = 7
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9851),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9856),
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9882),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9887),
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9918),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9922),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9949),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9958),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9985),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 202, DateTimeKind.Local).AddTicks(9989),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(16),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(20),
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(47),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(56),
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(82),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(87),
                            UserId = 20
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(113),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(118),
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(149),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(153),
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(180),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(185),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(211),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(220),
                            UserId = 10
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(247),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(251),
                            UserId = 13
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(278),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 203, DateTimeKind.Local).AddTicks(282),
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisCommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDisLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("DisCommentReactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDisLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("DisPostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(3571),
                            IsDisLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(4575),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5553),
                            IsDisLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5566),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5611),
                            IsDisLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5620),
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5651),
                            IsDisLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5655),
                            UserId = 20
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5686),
                            IsDisLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5691),
                            UserId = 9
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5722),
                            IsDisLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5726),
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5757),
                            IsDisLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5762),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5788),
                            IsDisLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5793),
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5824),
                            IsDisLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5828),
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5855),
                            IsDisLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5860),
                            UserId = 19
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5891),
                            IsDisLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5895),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5926),
                            IsDisLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5931),
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5962),
                            IsDisLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5966),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(5993),
                            IsDisLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6002),
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6028),
                            IsDisLike = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6033),
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6068),
                            IsDisLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6073),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6104),
                            IsDisLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6108),
                            UserId = 14
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6135),
                            IsDisLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6140),
                            UserId = 13
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6171),
                            IsDisLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6175),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6202),
                            IsDisLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 193, DateTimeKind.Local).AddTicks(6211),
                            UserId = 17
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 889, DateTimeKind.Local).AddTicks(4534),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/aka_james/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(5148)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6810),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/the_purplebunny/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6828)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6872),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mocabyte/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6877)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6903),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ffbel/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6912)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6935),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/adhiardana/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6943)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6966),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sainraja/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6970)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(6997),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/spedwig/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7001)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7028),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ahmadajmi/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7032)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7055),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gipsy_raf/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7063)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7086),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/overra/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7090)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7112),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/woodydotmx/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7121)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7143),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/liminha/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7148)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7170),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gt/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7179)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7201),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/amanruzaini/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7206)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7232),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dmitriychuta/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7237)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7259),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/amywebbb/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7263)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7299),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jarsen/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7308)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7335),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gmourier/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7339)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7361),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/vigobronx/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7366)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7392),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/buleswapnil/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 890, DateTimeKind.Local).AddTicks(7397)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(5045),
                            URL = "https://picsum.photos/640/480/?image=161",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6018)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6307),
                            URL = "https://picsum.photos/640/480/?image=777",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6320)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6356),
                            URL = "https://picsum.photos/640/480/?image=423",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6360)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6392),
                            URL = "https://picsum.photos/640/480/?image=1005",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6396)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6432),
                            URL = "https://picsum.photos/640/480/?image=62",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6436)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6463),
                            URL = "https://picsum.photos/640/480/?image=1071",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6467)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6494),
                            URL = "https://picsum.photos/640/480/?image=923",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6498)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6525),
                            URL = "https://picsum.photos/640/480/?image=384",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6529)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6556),
                            URL = "https://picsum.photos/640/480/?image=1011",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6560)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6587),
                            URL = "https://picsum.photos/640/480/?image=297",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6592)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6618),
                            URL = "https://picsum.photos/640/480/?image=765",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6623)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6649),
                            URL = "https://picsum.photos/640/480/?image=666",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6654)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6676),
                            URL = "https://picsum.photos/640/480/?image=148",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6685)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6707),
                            URL = "https://picsum.photos/640/480/?image=11",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6716)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6738),
                            URL = "https://picsum.photos/640/480/?image=136",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6747)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6769),
                            URL = "https://picsum.photos/640/480/?image=651",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6774)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6805),
                            URL = "https://picsum.photos/640/480/?image=978",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6814)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6836),
                            URL = "https://picsum.photos/640/480/?image=48",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6845)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6867),
                            URL = "https://picsum.photos/640/480/?image=351",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6872)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6898),
                            URL = "https://picsum.photos/640/480/?image=618",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 897, DateTimeKind.Local).AddTicks(6903)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 10,
                            Body = "Et dolores quis est dolor qui.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 159, DateTimeKind.Local).AddTicks(5415),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 159, DateTimeKind.Local).AddTicks(6340)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 12,
                            Body = @"Repudiandae quaerat culpa vel et.
Sed beatae labore corporis nisi ex qui quas earum.
Quis aspernatur sed quia perspiciatis et voluptas fugiat.
Numquam molestias et.
Aliquam architecto illo harum eligendi magni tempore.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(6953),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(6980)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 8,
                            Body = @"Quibusdam sequi explicabo enim omnis necessitatibus eius ut et aperiam.
Architecto exercitationem possimus ab recusandae.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7269),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7278)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 15,
                            Body = "Exercitationem totam maiores tempora nostrum.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7366),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7371)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 15,
                            Body = "Aut qui corrupti sed vel.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7433),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(7438)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 7,
                            Body = "cupiditate",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(8478),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(8491)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Consequatur eius quod.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(8633),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 160, DateTimeKind.Local).AddTicks(8638)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Body = "Voluptatem amet voluptatem libero et sit ipsum et. Illo amet pariatur. Et corporis nulla sed sint aut laboriosam cumque modi eos.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2269),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2286)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            Body = "Voluptas corrupti enim iure voluptas quis provident vero.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2384),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2393)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 13,
                            Body = "Ut consequatur quas dolor eos odio. Necessitatibus sint saepe. Quam molestiae quod ipsa quibusdam quae. Fuga commodi tempore ea vel. Libero quam natus iusto veritatis possimus cum libero.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2660),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2664)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "Sapiente qui id dolore assumenda pariatur deserunt et. Voluptas unde quos inventore et consequatur et ea maxime dolores. Quibusdam excepturi quisquam debitis id dolorem nesciunt numquam est incidunt. Earum impedit beatae vitae sed.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2971),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(2980)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 8,
                            Body = "Voluptas cumque culpa perferendis rerum alias quaerat accusamus molestiae. At nam nisi molestiae qui aut est facilis rerum. Vel explicabo id molestias id dolor reiciendis quam. Modi dolore voluptas qui sed. Consequatur eos et distinctio qui ut ut nisi in deleniti.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3309),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3313)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            Body = "harum",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3362),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3371)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            Body = "Et voluptate placeat delectus quasi voluptate neque voluptatem voluptas deserunt.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3451),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3460)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 21,
                            Body = "vitae",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3495),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3500)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Body = @"Maiores quia temporibus doloremque placeat suscipit doloremque sit esse.
Repellendus voluptas non omnis aut porro autem sed nulla.
Praesentium dolores et.
Facere eos illum.
Adipisci modi amet doloribus rem et.
Quo architecto autem repellat et ipsa.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3900),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3904)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "illo",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(3998),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4007)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 7,
                            Body = "Ut voluptas quibusdam saepe in. Voluptatem qui ad laborum occaecati natus. Consectetur quidem quibusdam quis.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4127),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4131)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            Body = "facilis",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4171),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4175)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 16,
                            Body = "accusantium",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4215),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 161, DateTimeKind.Local).AddTicks(4224)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(1366),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(2291),
                            UserId = 17
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3504),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3517),
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3562),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3571),
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3597),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3606),
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3633),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3642),
                            UserId = 10
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3669),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3673),
                            UserId = 15
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3704),
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3713),
                            UserId = 18
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3740),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3744),
                            UserId = 9
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3829),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3833),
                            UserId = 11
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3869),
                            IsLike = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3873),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3900),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3904),
                            UserId = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3935),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3940),
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3966),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(3971),
                            UserId = 6
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4002),
                            IsLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4006),
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4033),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4037),
                            UserId = 6
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4069),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4073),
                            UserId = 19
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4104),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4109),
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4140),
                            IsLike = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4144),
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4171),
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4180),
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4206),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 183, DateTimeKind.Local).AddTicks(4211),
                            UserId = 13
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 936, DateTimeKind.Local).AddTicks(2623),
                            Email = "Heather.Turner3@yahoo.com",
                            Password = "KwEGs/lmxaVuEzQYFtWybBe7ZZpD3KlYRO5blo63U5c=",
                            Salt = "0HnSOwpnTMk6pG530jA2qfJeiT/JgfFw/vc9aaxibLs=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 936, DateTimeKind.Local).AddTicks(3707),
                            UserName = "Ibrahim.Kuphal"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 946, DateTimeKind.Local).AddTicks(9983),
                            Email = "Kaylin_OConner@gmail.com",
                            Password = "l8LYqehV8G5ZNMQJBxhvrel0HA0HjzS+SvhJWD295kc=",
                            Salt = "KyV5CEXhijXQteYtFgUYT4IHMdLm/xpHm7TS5bYXNPM=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 947, DateTimeKind.Local).AddTicks(28),
                            UserName = "Amber.Renner64"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 957, DateTimeKind.Local).AddTicks(2063),
                            Email = "Amanda_Koch38@gmail.com",
                            Password = "ZN2UR2C2c0IJQnT0aQDFF/sY3ibpcSAeoTrNBvZlOP0=",
                            Salt = "aYS/WnEcbzl0nl2mhQPfluYVyqKOOwo/avtBiwKeeII=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 957, DateTimeKind.Local).AddTicks(2081),
                            UserName = "Dulce35"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 967, DateTimeKind.Local).AddTicks(5676),
                            Email = "Trey.Reynolds26@yahoo.com",
                            Password = "funDSo3BsIaDATbgtvXnRtDZE0skgH+gruip8al+dmk=",
                            Salt = "hvlxQoW8A4mYUrqPtIC99QsHIc+ShD7X3W/JbBK3vck=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 967, DateTimeKind.Local).AddTicks(5698),
                            UserName = "Jasen_DuBuque"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 977, DateTimeKind.Local).AddTicks(8859),
                            Email = "Kariane78@hotmail.com",
                            Password = "Hj0+FbUaI1FjveWqbrj9TIUmHrqlbOq7y7uuIrcnOwU=",
                            Salt = "H0cZXZXOhxfGtIlDggNa66ypJn80cjx7SRuue6m/sFE=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 977, DateTimeKind.Local).AddTicks(8899),
                            UserName = "Laura53"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 988, DateTimeKind.Local).AddTicks(5383),
                            Email = "Kiley.Wintheiser10@gmail.com",
                            Password = "VHmKTYHUAnfBMkrAJ5Ocq1fvAMUeKombu+CcTDzXzDc=",
                            Salt = "uI2rI0VOSK/kuprDtFJLLq25Ti6rfL3mZG6f9HcHN8k=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 988, DateTimeKind.Local).AddTicks(5410),
                            UserName = "Jensen33"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 998, DateTimeKind.Local).AddTicks(7024),
                            Email = "Brandon68@hotmail.com",
                            Password = "wfxPiFBgWelM08CX+q/rF+o3ckhOgtOoiIZSI/bgz0M=",
                            Salt = "6ED6/LaIIMApHpmJcVswgbsVsgqNAWugMsYuG4UaxEk=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 4, 998, DateTimeKind.Local).AddTicks(7041),
                            UserName = "Buster.Mohr"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 9, DateTimeKind.Local).AddTicks(6308),
                            Email = "Camille74@yahoo.com",
                            Password = "ZoSTQsajyw9dqeHYW/AZNTV/nFyn78NThNVlVFuk2tk=",
                            Salt = "siXZjlCEPXjjLuSmeIH6vDOF6W+rTpHbTLDqGSVO290=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 9, DateTimeKind.Local).AddTicks(6371),
                            UserName = "Amalia.Schiller"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 19, DateTimeKind.Local).AddTicks(8525),
                            Email = "Katherine.Zulauf21@hotmail.com",
                            Password = "yxO+LVV2ymu8ljgNyDqJFg7kAtqnnDBGkKWWUwC5xA8=",
                            Salt = "n+eWq35dvkcTDLLnv9p2GtdbLhs2xgQj+JJBEsCW1cw=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 19, DateTimeKind.Local).AddTicks(8543),
                            UserName = "Grace26"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 32, DateTimeKind.Local).AddTicks(375),
                            Email = "Melyna.Anderson@hotmail.com",
                            Password = "tV/f5RwN6dbWqM+3UFlvuYWLFLaJBugdhf+wt4EiDGw=",
                            Salt = "jmR5XLDnKuWtI2AzkZcxetv4zfz6jX5ZRaJnjD4blZw=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 32, DateTimeKind.Local).AddTicks(410),
                            UserName = "Haley.Windler"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 42, DateTimeKind.Local).AddTicks(4966),
                            Email = "Rocky12@gmail.com",
                            Password = "ZR6OWya2clSz/rNMwUEmFi+OR3SV4xx4po6pvuOZWgw=",
                            Salt = "7dRH4sjCqxOwW5ALIyyOKYHPE9rTw3zQ/RVmXDjg0pY=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 42, DateTimeKind.Local).AddTicks(4997),
                            UserName = "Mackenzie.Jacobi"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 52, DateTimeKind.Local).AddTicks(7326),
                            Email = "Hosea77@yahoo.com",
                            Password = "KIeRHcbNa9VQbn1NrRwoN5q7ZvGf40lg5FHmD/szw2c=",
                            Salt = "+kw9i4r63iTqMUg23SsDRaIurYzY+Ekzj48Djv6GWhU=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 52, DateTimeKind.Local).AddTicks(7348),
                            UserName = "Reyes7"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 63, DateTimeKind.Local).AddTicks(6535),
                            Email = "Toby_Berge@gmail.com",
                            Password = "QbiRzT8kVnbfxUKIY5yH/nGtCl1alH90ifNNlUIkmnY=",
                            Salt = "VuMUWjd4OONmiuejGtZ10O9ewFNE83qcqdXbGDsj8Ls=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 63, DateTimeKind.Local).AddTicks(6571),
                            UserName = "Dane_Heidenreich82"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 74, DateTimeKind.Local).AddTicks(8935),
                            Email = "Jamil26@yahoo.com",
                            Password = "GX/YhjgbOqUZkoYc/QhQdfVjXT4oa/iR2Fi2YROtrIg=",
                            Salt = "Ja+MtcDb3N0j+bpHe9YwfjcnukNNeqdnFuLEPGZk8P0=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 74, DateTimeKind.Local).AddTicks(8971),
                            UserName = "Ramiro.Jacobi50"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 85, DateTimeKind.Local).AddTicks(633),
                            Email = "Cristopher12@hotmail.com",
                            Password = "zMBYj3LHmjL56k6hoAl5lD4Ui2c4+Im9SAIxucZrBWo=",
                            Salt = "AMhKc0zk/AohshkuNnN5biGBWoomMGp6Bil7Kb/6aig=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 85, DateTimeKind.Local).AddTicks(646),
                            UserName = "Agustina_Haley"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 95, DateTimeKind.Local).AddTicks(2695),
                            Email = "Dereck67@hotmail.com",
                            Password = "JD1bBO+FfjGAx+yQvjF6Xo1gYzeiSuD8k8u3Ai7VF20=",
                            Salt = "RNXlsi9DKuQoCZDW9y8sYO8Qx3YKUe/+/1dOytrVQVA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 95, DateTimeKind.Local).AddTicks(2708),
                            UserName = "Susie.Sanford"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 105, DateTimeKind.Local).AddTicks(7988),
                            Email = "Regan.Muller49@hotmail.com",
                            Password = "68nsiIqwCPWQXJjMefqZ85AOtUJIU9sWJesHJEOZQ2M=",
                            Salt = "XR2DGf3JG++pBOgsxaSkg6yfrfrvtl7XrdrPE7sPD7A=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 105, DateTimeKind.Local).AddTicks(8024),
                            UserName = "Ayden_Weimann"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 115, DateTimeKind.Local).AddTicks(9433),
                            Email = "Oda_Schaden@gmail.com",
                            Password = "pbLUa9lhLpBJnWy9xZZ8kae0Qc6Tn6j0lva35GBiDPo=",
                            Salt = "EaTV3HozYn0iIN8lYkkH3NTv+7Mi3zr3pYgNT/lCQck=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 115, DateTimeKind.Local).AddTicks(9446),
                            UserName = "Maegan_Ward28"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 126, DateTimeKind.Local).AddTicks(1024),
                            Email = "Cora_Okuneva27@gmail.com",
                            Password = "GQH0hny4aDOD+fxYI5f4kwDmRHm6J2JJ/RVvW4CxCpc=",
                            Salt = "Vnzu6h582SX5w4dhLU3KjXdRiBqeF7G8GltsuTva6BA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 126, DateTimeKind.Local).AddTicks(1046),
                            UserName = "Jaida.Brekke1"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 136, DateTimeKind.Local).AddTicks(6624),
                            Email = "Destini.Reichert@yahoo.com",
                            Password = "BQobkZUlj2L6lmIJsBi5Q8s3yO7GaD2PTfx9tOL5zzc=",
                            Salt = "m/wiNqf7cvMFBw3alelYg0/1clP5puK9ulhB3vaXuLA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 136, DateTimeKind.Local).AddTicks(6659),
                            UserName = "Damon_DuBuque"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 146, DateTimeKind.Local).AddTicks(8620),
                            Email = "test@gmail.com",
                            Password = "hc8NEdS+j/m+rx4YS3s57asHiyq74IAJCbMdPEM2slw=",
                            Salt = "CK/eUt3HTrORwlCrKkZvVtVxzBHKdgR0WG+mTFYAMWw=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 17, 5, 146, DateTimeKind.Local).AddTicks(8620),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisCommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("DisReactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
