// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190617121022_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            Body = "Magni vero velit qui.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 977, DateTimeKind.Local).AddTicks(7712),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 977, DateTimeKind.Local).AddTicks(8690)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 10,
                            Body = "Ratione est reiciendis.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 977, DateTimeKind.Local).AddTicks(9788),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 977, DateTimeKind.Local).AddTicks(9801)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 12,
                            Body = "Est quam cumque neque velit quia at consequatur magnam aut.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 977, DateTimeKind.Local).AddTicks(9925),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(5)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Body = "Commodi aut qui asperiores.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(104),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(113)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            Body = "Id ipsa magni.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(166),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(170)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 17,
                            Body = "Sed quaerat id ex voluptate sit laudantium ipsa minus non.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(250),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(255)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 12,
                            Body = "Eos ducimus dolor aut nulla distinctio sed rerum et veritatis.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(335),
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(344)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 6,
                            Body = "Sit reprehenderit eum est nostrum quam culpa voluptatum quidem mollitia.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(419),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(424)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "Occaecati iste magni et quibusdam aut molestiae.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(557),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(561)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Nihil nesciunt veniam fuga totam doloribus sint.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(633),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(637)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            Body = "Praesentium quo quasi distinctio consequuntur et commodi corrupti.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(708),
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(717)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 16,
                            Body = "Repudiandae maiores et eos natus vel doloribus ut omnis.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(793),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(797)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Body = "Est a ducimus consequatur autem fugit atque porro in.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(873),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(877)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 19,
                            Body = "Nobis atque totam quas.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(988),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(993)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 11,
                            Body = "Sed quia voluptas excepturi quia eaque.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1055),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1059)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 12,
                            Body = "Non non velit reiciendis.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1113),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1117)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            Body = "Cumque cum sint similique autem.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1170),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1179)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 11,
                            Body = "Illum quibusdam aut qui architecto ut.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1241),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1246)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 6,
                            Body = "Quis consequatur est consequatur ducimus.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1299),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1304)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            Body = "Quia nemo repellendus rem soluta.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1415),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 978, DateTimeKind.Local).AddTicks(1424)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 16, DateTimeKind.Local).AddTicks(8557),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 16, DateTimeKind.Local).AddTicks(9975),
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1295),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1317),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1392),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1401),
                            UserId = 15
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1459),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1472),
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1530),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1539),
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1597),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1606),
                            UserId = 20
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1664),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1672),
                            UserId = 18
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1730),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1739),
                            UserId = 21
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1797),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1806),
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1864),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1872),
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1926),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1939),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(1992),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2006),
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2055),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2068),
                            UserId = 11
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 3,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2126),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2135),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2192),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2201),
                            UserId = 20
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2255),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2264),
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2321),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2330),
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2388),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2397),
                            UserId = 12
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2455),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2464),
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2521),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 17, DateTimeKind.Local).AddTicks(2530),
                            UserId = 14
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDisLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("DisPostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(7170),
                            IsDisLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(8259),
                            UserId = 19
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9299),
                            IsDisLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9312),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9388),
                            IsDisLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9397),
                            UserId = 9
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9450),
                            IsDisLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9459),
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9504),
                            IsDisLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9512),
                            UserId = 14
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9575),
                            IsDisLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9588),
                            UserId = 11
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9668),
                            IsDisLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9686),
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9797),
                            IsDisLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9815),
                            UserId = 17
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9890),
                            IsDisLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9904),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9966),
                            IsDisLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 2, DateTimeKind.Local).AddTicks(9975),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(370),
                            IsDisLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(392),
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(499),
                            IsDisLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(508),
                            UserId = 18
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(579),
                            IsDisLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(588),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(646),
                            IsDisLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(659),
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(712),
                            IsDisLike = true,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(726),
                            UserId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(784),
                            IsDisLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(792),
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(850),
                            IsDisLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(859),
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(917),
                            IsDisLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(930),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(988),
                            IsDisLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(1001),
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(1059),
                            IsDisLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 22, 3, DateTimeKind.Local).AddTicks(1068),
                            UserId = 12
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 698, DateTimeKind.Local).AddTicks(1920),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/svenlen/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(1808)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3204),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mtolokonnikov/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3222)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3262),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ivanfilipovbg/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3271)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3293),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/chadengle/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3302)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3324),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/petrangr/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3328)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3355),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/cadikkara/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3360)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3382),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/doronmalki/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3391)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3413),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/nellleo/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3417)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3444),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jennyyo/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3448)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3471),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/Chakintosh/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3475)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3497),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/brandonflatsoda/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3506)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3528),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rez___a/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3533)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3555),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/thedamianhdez/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3564)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3586),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/reabo101/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3591)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3613),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ostirbu/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3617)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3640),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kalmerrautam/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3648)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3671),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/slowspock/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3675)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3786),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/flashmurphy/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3791)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3813),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mattsapii/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3822)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3844),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/darcystonge/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 699, DateTimeKind.Local).AddTicks(3848)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(5266),
                            URL = "https://picsum.photos/640/480/?image=682",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6333)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6644),
                            URL = "https://picsum.photos/640/480/?image=656",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6657)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6689),
                            URL = "https://picsum.photos/640/480/?image=149",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6693)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6720),
                            URL = "https://picsum.photos/640/480/?image=39",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6724)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6751),
                            URL = "https://picsum.photos/640/480/?image=475",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6755)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6782),
                            URL = "https://picsum.photos/640/480/?image=1033",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6786)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6813),
                            URL = "https://picsum.photos/640/480/?image=660",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6817)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6840),
                            URL = "https://picsum.photos/640/480/?image=942",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6849)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6871),
                            URL = "https://picsum.photos/640/480/?image=155",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6875)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6902),
                            URL = "https://picsum.photos/640/480/?image=521",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6906)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6933),
                            URL = "https://picsum.photos/640/480/?image=658",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(6991)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7017),
                            URL = "https://picsum.photos/640/480/?image=838",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7022)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7049),
                            URL = "https://picsum.photos/640/480/?image=704",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7053)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7075),
                            URL = "https://picsum.photos/640/480/?image=693",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7084)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7106),
                            URL = "https://picsum.photos/640/480/?image=351",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7111)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7137),
                            URL = "https://picsum.photos/640/480/?image=914",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7142)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7169),
                            URL = "https://picsum.photos/640/480/?image=919",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7173)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7195),
                            URL = "https://picsum.photos/640/480/?image=985",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7200)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7226),
                            URL = "https://picsum.photos/640/480/?image=1014",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7231)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7294),
                            URL = "https://picsum.photos/640/480/?image=590",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 706, DateTimeKind.Local).AddTicks(7298)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 11,
                            Body = "mollitia",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 964, DateTimeKind.Local).AddTicks(3424),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 964, DateTimeKind.Local).AddTicks(4415)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 21,
                            Body = "iure",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 964, DateTimeKind.Local).AddTicks(5433),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 964, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 11,
                            Body = "Voluptas aut consequatur nulla itaque beatae aut voluptatum qui sint. Quis iusto et magnam laudantium ut vel consectetur enim. Perferendis voluptatum et veniam odit omnis voluptatem sit.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(1735),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(1779)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 13,
                            Body = @"Consequatur et sint.
Quo fugiat tempore et expedita dolores suscipit.
Qui perferendis doloribus et dolores.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(3708),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(3726)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Body = "Sit dolor natus eum cupiditate. Nostrum voluptatem quam eius voluptates sit quos ducimus unde nisi. Ea rerum eaque ea nisi exercitationem aut cupiditate.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(4046),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(4050)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 15,
                            Body = "Voluptates eaque occaecati rerum eligendi totam id veritatis aut.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6455),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6472)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 20,
                            Body = "Quo fugit in aliquam occaecati ut autem.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6646),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6650)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 21,
                            Body = "eius",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6695),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6699)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 12,
                            Body = "Nemo maiores tenetur accusantium ullam excepturi sit. Dignissimos et reiciendis consequatur minima repellendus. Tenetur cumque at. Sit sunt ut sit quos rerum inventore doloribus. Ullam nihil id deleniti at voluptatum in voluptatem minus. Quia sed non aut vel.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6988),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(6997)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            Body = @"Dolorem ut deleniti aut.
Cumque perferendis ipsa ut laudantium.
Labore occaecati commodi sunt.
Veritatis et tenetur et non id eius iure.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7152),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7157)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            Body = "Blanditiis ullam non voluptatem unde vero et.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7232),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7237)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 14,
                            Body = @"Laudantium sed ut enim.
Ut soluta error et.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7366),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7375)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 20,
                            Body = "laborum",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7415),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7419)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 10,
                            Body = "Explicabo praesentium recusandae.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7477),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7481)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            Body = @"Dolorem eligendi nam impedit inventore sint nihil.
Quibusdam suscipit cum iure hic eius.
Maxime est rerum vel quidem et nihil quo.
Modi maiores magni quia sit impedit perferendis hic cum id.
Minima sit vero eos natus.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7810),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(7819)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 19,
                            Body = "Ipsa aspernatur debitis dolor. Possimus consequatur sed aperiam. Sed at est atque architecto eum magnam velit. Quia est quo.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8024),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8032)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 19,
                            Body = "Fugiat omnis qui ea amet necessitatibus laudantium eligendi.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8104),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8112)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            Body = "Repellat hic quia maxime rerum et.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8170),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8179)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 11,
                            Body = "Temporibus quia maiores atque est.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8237),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8241)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 7,
                            Body = "Alias eum blanditiis molestiae doloremque eum harum atque incidunt reprehenderit.",
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8321),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 967, DateTimeKind.Local).AddTicks(8330)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(1673),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(3033),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5264),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5291),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5366),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5371),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5402),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5411),
                            UserId = 15
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5442),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5446),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5477),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5482),
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5508),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5517),
                            UserId = 15
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5544),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5553),
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5588),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5597),
                            UserId = 20
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5651),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5664),
                            UserId = 16
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5722),
                            IsLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5731),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5904),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5913),
                            UserId = 18
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5975),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(5984),
                            UserId = 14
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6037),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6046),
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6104),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6113),
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6166),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6175),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6251),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6277),
                            UserId = 10
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6326),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6335),
                            UserId = 13
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6384),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6393),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6451),
                            IsLike = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 990, DateTimeKind.Local).AddTicks(6464),
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 745, DateTimeKind.Local).AddTicks(4262),
                            Email = "Stephania_Reynolds@hotmail.com",
                            Password = "DV3RfSAIWZiOnWWimckn0YDdPWi0hk3rPOmz0/rZlkY=",
                            Salt = "lCCcNyCxQnA2eHfF9Wr11LlYjN1syVIiYQN5kpYdOBQ=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 745, DateTimeKind.Local).AddTicks(5347),
                            UserName = "Jaycee_Abbott"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 755, DateTimeKind.Local).AddTicks(8920),
                            Email = "Amber13@yahoo.com",
                            Password = "2QTlWpPfHc6utxTPWBoqV6GyF27x2RFjFkbzlrnP0u8=",
                            Salt = "s4NxsxdikJXnzHhEifXyI6Z6b5TRn8L+lwSmrdI/O8w=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 755, DateTimeKind.Local).AddTicks(8943),
                            UserName = "Toby_Hayes"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 765, DateTimeKind.Local).AddTicks(9658),
                            Email = "Perry78@hotmail.com",
                            Password = "+TjsBFKpsEirTppkTgHA4NRxnuEOni8QMEG36HOwo3k=",
                            Salt = "5/vjS6PWR5Pqv8S29pxhmnWgK6vB4A9IyAMhZ71IQmg=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 765, DateTimeKind.Local).AddTicks(9680),
                            UserName = "Daniela.Jenkins7"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 776, DateTimeKind.Local).AddTicks(409),
                            Email = "Juston.Zemlak20@gmail.com",
                            Password = "R3wu0pzwXy0dFcLMVB1CGMNdFrG+Y/LkBwl2j22BHLM=",
                            Salt = "GQPkn0mLYyGYAds6gHCNz9LZ8rFPb+05FwgKLKgUAas=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 776, DateTimeKind.Local).AddTicks(436),
                            UserName = "Susan36"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 786, DateTimeKind.Local).AddTicks(1703),
                            Email = "Hector.Hermiston@hotmail.com",
                            Password = "JGklaZOVjagqDn3/8aAn5KdVlYkOim6pGGQptgkEVvY=",
                            Salt = "VHibLUE+le3bw2v6NPckVJMWvjD7fTkViYsIZ0y7wS4=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 786, DateTimeKind.Local).AddTicks(1721),
                            UserName = "Cali.Hand50"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 796, DateTimeKind.Local).AddTicks(4254),
                            Email = "Jensen_Sanford96@gmail.com",
                            Password = "LgNcGg/V4J6hvwb8Ltx/tU8f0F5PDnif3AUhKdMqFFM=",
                            Salt = "TCqD7fc3Bv+DlLiBM20rhy/OSnwvJDrJy7EjCqN80tA=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 796, DateTimeKind.Local).AddTicks(4285),
                            UserName = "Angie36"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 806, DateTimeKind.Local).AddTicks(4684),
                            Email = "Marcus83@yahoo.com",
                            Password = "T03/VIGWAiOBrd1lW3CSXpX4BclAiK+ChxIHaq1ua8Q=",
                            Salt = "P3onZ3mHOmkD4hYK87Ekw/4tkt0qXfionB7/Yj9OKhA=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 806, DateTimeKind.Local).AddTicks(4702),
                            UserName = "Diamond_Heller"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 816, DateTimeKind.Local).AddTicks(4796),
                            Email = "Virgie.Willms32@yahoo.com",
                            Password = "YAYoVRyjSydOu6U81mnLz16HvQl6jtwOzAJQFGH0lT0=",
                            Salt = "tnFpn8s9Bbb5Pz/FVVh/kQqzT/yFDEFhIVK6aItImyo=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 816, DateTimeKind.Local).AddTicks(4805),
                            UserName = "Madeline_Shanahan"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 826, DateTimeKind.Local).AddTicks(8032),
                            Email = "Amani11@hotmail.com",
                            Password = "iUyW1f4xkAsJ5jMU6PzEOrf/uLKVUp7VGOXuaxW+7Fc=",
                            Salt = "PVI+RfI8midbnnXBZNNxy2HJ4hk4hMXKz0bxIsTS9NM=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 826, DateTimeKind.Local).AddTicks(8054),
                            UserName = "Krista51"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 837, DateTimeKind.Local).AddTicks(2290),
                            Email = "Gina5@yahoo.com",
                            Password = "NNtAKDXwmaPZZc3fYF2y0KLiCvdcRlhCQV8QEoP57wI=",
                            Salt = "Hsihg0gNfmPdVXQP9b6hQdQvwD7p96wgn+JOpBky2dg=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 837, DateTimeKind.Local).AddTicks(2316),
                            UserName = "Emma_Hegmann60"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 847, DateTimeKind.Local).AddTicks(2760),
                            Email = "Evan_White9@yahoo.com",
                            Password = "yB50TKS8p85ZrdGkB+SaWfA1/rxaP5FDOPiDFhF4ezM=",
                            Salt = "yV8Td3HKfvxGmuBs8zRf5IqBjSBgRbXwya5rldqI4Wg=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 847, DateTimeKind.Local).AddTicks(2778),
                            UserName = "Jamel_Veum41"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 857, DateTimeKind.Local).AddTicks(4574),
                            Email = "Camylle.Haley@gmail.com",
                            Password = "VBIUAtuCDlj741s9M3ABzLlZgKTqAOGy/cc5ES4a/+0=",
                            Salt = "8UfLrcGYv9pb6c5hldd+q5FIpzG9dqSccWZVqbcJvaA=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 857, DateTimeKind.Local).AddTicks(4591),
                            UserName = "Devante_Simonis"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 867, DateTimeKind.Local).AddTicks(5392),
                            Email = "Retha_Considine53@gmail.com",
                            Password = "lQH3Y1kUjuA6eMoHDvkkXAG2xcIg5sJ3I2eNAZNfwgw=",
                            Salt = "eR9E6MEZ5ZDXyyeH78IAcDag+Kpj/jlrzZFb0EcfsMk=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 867, DateTimeKind.Local).AddTicks(5414),
                            UserName = "Jolie_Howell"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 879, DateTimeKind.Local).AddTicks(4743),
                            Email = "Arch_Moen15@gmail.com",
                            Password = "QyGZ0YccVoqlinVc/fUFN0IopNudmF/oISidbigCVeQ=",
                            Salt = "5Jy4dbdZDiZw7kf1AUAHwwErYb89NLXfhO05/gtD1qk=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 879, DateTimeKind.Local).AddTicks(4779),
                            UserName = "Abraham_Sauer"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 890, DateTimeKind.Local).AddTicks(1169),
                            Email = "Arnold.Doyle55@yahoo.com",
                            Password = "5igdHvSGa72JFdKswPTs71tLc0CzKH93K9ThimyJXDY=",
                            Salt = "uc2n+dpMJAG99I6x3BYmWOmFvc9sn2P0A7cyrc/ejcs=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 890, DateTimeKind.Local).AddTicks(1209),
                            UserName = "Carolanne.Beahan6"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 901, DateTimeKind.Local).AddTicks(7179),
                            Email = "Shaun.Koch76@yahoo.com",
                            Password = "cjPAfzDaL7/MlWHUkQ7faaeM3knTA5RuS2QJP8QA7TQ=",
                            Salt = "EvA2+vLG0S7nnrEdBBTJo+2r1B/7CbqgEpF0rMLhNXY=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 901, DateTimeKind.Local).AddTicks(7223),
                            UserName = "Jovan73"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 912, DateTimeKind.Local).AddTicks(5249),
                            Email = "Dario_Heller@gmail.com",
                            Password = "UqTfWqmp39hu368vFsFiQB54JD6tZyrdPUPJBFl3vSA=",
                            Salt = "ZHtBzKkLeE6gGTWd4wlsXGFERK4aO1IdLIx0z2JHFb4=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 912, DateTimeKind.Local).AddTicks(5276),
                            UserName = "Renee.Feeney"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 922, DateTimeKind.Local).AddTicks(6760),
                            Email = "Pedro_Lemke@gmail.com",
                            Password = "FpN0XtFLvSjgFcZAsiJ7TMzP7XgPQXeoII2L06a8VaM=",
                            Salt = "uchRnlu4H39IT+ud5ivreGvZms8qoU1k8micz4fKj+Y=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 922, DateTimeKind.Local).AddTicks(6778),
                            UserName = "Rosalind.Kuhic"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 932, DateTimeKind.Local).AddTicks(7321),
                            Email = "Alexane.Kemmer@gmail.com",
                            Password = "RmdIsnq0Oq/AzJzogMgyE73ERhHNkqaH86YyCpf2rWY=",
                            Salt = "QEnukf3U/7iXCuu7aK89EnP+w3Mrw18+ufRisRto59E=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 932, DateTimeKind.Local).AddTicks(7347),
                            UserName = "Eulah.Dietrich95"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 942, DateTimeKind.Local).AddTicks(9236),
                            Email = "Barney_Zemlak52@gmail.com",
                            Password = "jfYuDlFjocB77RLG9ShExVNTPZaSLu5pm2poyR9vBEM=",
                            Salt = "W94Ok0Y2lPfRmaRbkSChj5Mhcw3gZLBrMj7D3Xz+BbQ=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 942, DateTimeKind.Local).AddTicks(9263),
                            UserName = "Rocky43"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 952, DateTimeKind.Local).AddTicks(9308),
                            Email = "test@gmail.com",
                            Password = "tlsRD84IM9CUB+apKtjuui7neJwZKiVypKAKdWMgrZQ=",
                            Salt = "kodLmlV4z1U/aXmRRuqY20LbaapJt1QJ4zlEOwAB2To=",
                            UpdatedAt = new DateTime(2019, 6, 17, 15, 10, 21, 952, DateTimeKind.Local).AddTicks(9308),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("DisReactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
