// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190617223401_DisReactions")]
    partial class DisReactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 7,
                            Body = "Ratione porro qui error voluptatem itaque non molestiae excepturi.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(3185),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(4141)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "Sed rem dignissimos omnis dolores voluptatem natus vitae voluptatem quam.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5225),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5239)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 18,
                            Body = "Eum iste suscipit eos cum optio eum.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5399),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5407)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 13,
                            Body = "Deserunt fugiat numquam esse quia.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5474),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5479)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 17,
                            Body = "Eaque dignissimos quas autem consequatur voluptates laboriosam quia quisquam.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5559),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5563)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Body = "Est aut rem veritatis debitis eum adipisci.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5630),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5639)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            Body = "Perspiciatis aut nihil sed at porro veniam ut.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5705),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5714)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Body = "Qui nam vel repellat.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5803),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5807)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 14,
                            Body = "Occaecati rem reiciendis inventore illum at.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5874),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5879)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 21,
                            Body = "Voluptatem sed itaque reprehenderit sit.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5936),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(5945)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "Ea tempore dolore inventore dolorum molestiae illum sed et vel.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6021),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6025)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            Body = "Et accusamus adipisci assumenda perspiciatis commodi expedita corrupti.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6096),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6101)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            Body = "Enim ex magni consequatur ullam odit.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6270),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6279)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 19,
                            Body = "Repudiandae mollitia suscipit earum consequatur.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6341),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6350)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            Body = "Cupiditate voluptatem rem atque.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6399),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6407)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 10,
                            Body = "Nam maxime fuga.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6456),
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6461)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Body = "Velit sed illum facere repellendus voluptatem autem ducimus ut.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6536),
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6541)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            Body = "Dicta quod totam sed magnam in facilis.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6621),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6625)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 21,
                            Body = "Delectus vel aut eaque et quae nihil omnis atque est.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6772),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6776)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 7,
                            Body = "Voluptatum sint amet qui quidem facere quo.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6847),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 376, DateTimeKind.Local).AddTicks(6852)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(6403),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(7314),
                            UserId = 15
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8323),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8336),
                            UserId = 20
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8381),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8385),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8416),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8425),
                            UserId = 17
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8452),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8456),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8487),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8492),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8523),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8527),
                            UserId = 19
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8558),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8563),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8594),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8598),
                            UserId = 18
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8625),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8634),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8661),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8665),
                            UserId = 10
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8696),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8701),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8727),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8736),
                            UserId = 18
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8763),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8767),
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8794),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8803),
                            UserId = 21
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8830),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8834),
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8861),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8870),
                            UserId = 11
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8896),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8901),
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8932),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8936),
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8963),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 407, DateTimeKind.Local).AddTicks(8972),
                            UserId = 13
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisCommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDisLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("DisCommentReactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsDisLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("DisPostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(1012),
                            IsDisLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(1932),
                            UserId = 9
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2888),
                            IsDisLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2906),
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2946),
                            IsDisLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2955),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2986),
                            IsDisLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(2990),
                            UserId = 18
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3021),
                            IsDisLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3026),
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3052),
                            IsDisLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3057),
                            UserId = 14
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3088),
                            IsDisLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3097),
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3123),
                            IsDisLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3128),
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3159),
                            IsDisLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3163),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3195),
                            IsDisLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3199),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3230),
                            IsDisLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3235),
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3261),
                            IsDisLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3270),
                            UserId = 10
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3297),
                            IsDisLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3301),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3328),
                            IsDisLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3337),
                            UserId = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3363),
                            IsDisLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3368),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3399),
                            IsDisLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3403),
                            UserId = 15
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3430),
                            IsDisLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3439),
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3466),
                            IsDisLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3470),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3497),
                            IsDisLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3506),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3532),
                            IsDisLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 398, DateTimeKind.Local).AddTicks(3537),
                            UserId = 18
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 36, DateTimeKind.Local).AddTicks(2811),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/krystalfister/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(2832)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4415),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/franciscoamk/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4428)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4477),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/magugzbrand2d/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4481)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4508),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sementiy/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4512)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4539),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/peterlandt/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4543)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4566),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gipsy_raf/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4570)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4592),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jamiebrittain/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4601)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4623),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/Silveredge9/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4628)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4650),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rangafangs/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4655)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4677),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/snowshade/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4686)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4708),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/agromov/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4712)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4739),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/danvernon/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4743)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4766),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/betraydan/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4770)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4792),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/d_kobelyatsky/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4801)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4823),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/wearesavas/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4828)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4850),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/allfordesign/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4855)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4877),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/thatonetommy/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4881)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4908),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kaelifa/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4912)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4935),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/danro/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4939)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4961),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jerrybai1907/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 37, DateTimeKind.Local).AddTicks(4970)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(374),
                            URL = "https://picsum.photos/640/480/?image=373",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1463)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1841),
                            URL = "https://picsum.photos/640/480/?image=177",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1854)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1890),
                            URL = "https://picsum.photos/640/480/?image=1056",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1894)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1921),
                            URL = "https://picsum.photos/640/480/?image=100",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1926)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1952),
                            URL = "https://picsum.photos/640/480/?image=712",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1957)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(1997),
                            URL = "https://picsum.photos/640/480/?image=27",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2001)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2028),
                            URL = "https://picsum.photos/640/480/?image=755",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2032)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2054),
                            URL = "https://picsum.photos/640/480/?image=750",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2063)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2086),
                            URL = "https://picsum.photos/640/480/?image=816",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2090)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2117),
                            URL = "https://picsum.photos/640/480/?image=143",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2121)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2143),
                            URL = "https://picsum.photos/640/480/?image=805",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2152)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2174),
                            URL = "https://picsum.photos/640/480/?image=728",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2179)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2206),
                            URL = "https://picsum.photos/640/480/?image=256",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2210)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2232),
                            URL = "https://picsum.photos/640/480/?image=940",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2241)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2263),
                            URL = "https://picsum.photos/640/480/?image=955",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2268)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2294),
                            URL = "https://picsum.photos/640/480/?image=591",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2299)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2321),
                            URL = "https://picsum.photos/640/480/?image=705",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2330)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2361),
                            URL = "https://picsum.photos/640/480/?image=286",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2366)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2392),
                            URL = "https://picsum.photos/640/480/?image=171",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2397)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2423),
                            URL = "https://picsum.photos/640/480/?image=439",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 44, DateTimeKind.Local).AddTicks(2428)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "Qui libero voluptatem voluptate occaecati assumenda.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 364, DateTimeKind.Local).AddTicks(216),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 364, DateTimeKind.Local).AddTicks(1331)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 20,
                            Body = "Officiis reprehenderit tempora repellat ea nihil et. Dolorum omnis quaerat et et consectetur consectetur aliquid et. Maiores illo cupiditate nihil quia.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(3950),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(3994)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 14,
                            Body = "deserunt",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(5870),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(5901)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 8,
                            Body = "rerum",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(6172),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(6194)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 15,
                            Body = "Itaque id id fugiat. Autem aut quisquam eos accusamus incidunt eius sit. Voluptatem vel dolorem eaque voluptatibus ipsum. Facilis illo laboriosam fugit. Ipsum ducimus dolores quo laudantium. Quam tenetur esse.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7101),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7118)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 19,
                            Body = "reprehenderit",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7216),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7225)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 16,
                            Body = "Architecto fugiat autem non incidunt at.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7465),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7487)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 9,
                            Body = "Animi ab nostrum omnis voluptatem porro ullam dolorum ea qui.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7696),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(7714)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "et",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8074),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8087)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 14,
                            Body = "qui",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8181),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8190)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 20,
                            Body = "Cumque quia reiciendis molestias quod.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8376),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 365, DateTimeKind.Local).AddTicks(8385)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            Body = @"Neque dolor illum et quia omnis voluptate odio explicabo odit.
Ut perferendis libero nam in fugiat incidunt.
Nobis illo et et sit ut dicta in facere.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(456),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(470)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Body = @"Iusto et asperiores voluptatibus rem.
Et id tempora omnis qui qui et adipisci nemo nulla.
Voluptatem impedit quod fuga.
Excepturi unde atque iste eaque amet et laudantium rerum nihil.
Dolorum in molestiae tempore deserunt ea aliquid est hic.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(892),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(901)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            Body = "Unde necessitatibus ut voluptates consequatur eum aut.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1012),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1016)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 21,
                            Body = "Dignissimos dolores repudiandae voluptas illo vitae voluptas est.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1145),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1154)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 4,
                            Body = "et",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1194),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1198)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 11,
                            Body = @"Magni cum fugit voluptate veritatis.
Aut ratione et maxime expedita sed qui placeat delectus beatae.
Tempora explicabo dignissimos molestias iste et veritatis dolores.
Facilis consequatur enim eum id incidunt accusamus et saepe.
Iure quia eum laborum et eligendi dolores laboriosam odit corrupti.
Non numquam ut sit rerum.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1518),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1527)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            Body = "Ab repudiandae nostrum et rerum officiis sed consequatur nihil. Fugiat at voluptatibus est. Nulla deleniti ut vel quam non. Consequatur quas iusto sequi minus sed temporibus placeat ex assumenda. Quia suscipit voluptate explicabo quis.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1803),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1812)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 8,
                            Body = @"Labore et ex incidunt pariatur consequatur aut alias.
Aperiam sequi minima aspernatur voluptates repellendus consequatur corrupti qui suscipit.
Tempore saepe et sed.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1954),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(1958)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Body = "Enim asperiores dolorem. Enim voluptas quasi beatae. Aut qui est placeat vel id neque saepe labore dolores. Natus omnis cum voluptatem fugit. Ut consequatur qui. Dolores quo aliquid necessitatibus cumque eaque.",
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(2198),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 366, DateTimeKind.Local).AddTicks(2203)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(5656),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(6585),
                            UserId = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7652),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7670),
                            UserId = 13
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7714),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7718),
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7750),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7758),
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7785),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7794),
                            UserId = 10
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7821),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7825),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7856),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7861),
                            UserId = 15
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7887),
                            IsLike = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7892),
                            UserId = 13
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7954),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7958),
                            UserId = 21
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7990),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(7994),
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8025),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8030),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8061),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8123),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8158),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8163),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8194),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8198),
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8225),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8234),
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8261),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8265),
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8296),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8301),
                            UserId = 18
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8327),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8336),
                            UserId = 21
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8363),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8367),
                            UserId = 16
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8398),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 388, DateTimeKind.Local).AddTicks(8403),
                            UserId = 16
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 90, DateTimeKind.Local).AddTicks(4926),
                            Email = "Bettie.Watsica42@hotmail.com",
                            Password = "oSVpQATzIlhoqd0GxrpMSaVW32st0gsb4UCTqJHWW9w=",
                            Salt = "O+P0+Fk0YORSgHmhQfqX54wANzkVFRAKWjVnfmTCNXk=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 90, DateTimeKind.Local).AddTicks(6912),
                            UserName = "Flavio.Blick10"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 109, DateTimeKind.Local).AddTicks(4282),
                            Email = "Dolores_Hane85@yahoo.com",
                            Password = "o0xI9+zROaYc8ogVwwUNEHRx2dolcQvz5RrGJ34vx0w=",
                            Salt = "ybUxO9C7kq7U5UIthkMOKmI4NEU6ZzsEM6qNGF9/2zA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 109, DateTimeKind.Local).AddTicks(4327),
                            UserName = "Lizzie87"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 121, DateTimeKind.Local).AddTicks(2953),
                            Email = "Estefania.Jacobi67@gmail.com",
                            Password = "/WzLbfkMv/C7IHL98yRqFSU2EQN/9y/IKbt5+NvOazw=",
                            Salt = "5GNkvsFuce/tfRfqhE2SHQvwqUIWTVCLw9pzx8DTWAA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 121, DateTimeKind.Local).AddTicks(2993),
                            UserName = "Deondre_Schroeder"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 139, DateTimeKind.Local).AddTicks(6433),
                            Email = "Selmer_McGlynn7@hotmail.com",
                            Password = "qmdhvUvrNngEy/VtbviKmghlD6qx5UXTZ58WJenmsB8=",
                            Salt = "21b/CW/7F6VkZz+MLpx7evK+22+8gXI0d9ZLSmwbGM0=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 139, DateTimeKind.Local).AddTicks(6486),
                            UserName = "Korbin_Prohaska"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 159, DateTimeKind.Local).AddTicks(1006),
                            Email = "Odie_MacGyver78@yahoo.com",
                            Password = "i7yBUoPs2s+4emNFnr71rXMLu9hxTLXIukS2z6OBVpY=",
                            Salt = "c2TKMKo1yhrFF2fw3IzooXqRghePg5A+iXT/StlbvMo=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 159, DateTimeKind.Local).AddTicks(1055),
                            UserName = "Trisha.Kautzer"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 171, DateTimeKind.Local).AddTicks(7891),
                            Email = "Cesar.Schroeder@yahoo.com",
                            Password = "s+no5+tL6Jb2Hgl4ITc+r8ISOdyjm6lervj3aZC3+Mo=",
                            Salt = "6PgHF+A6OjOulq1dzdKDI0xckkKVBDKBfvG5s954kRI=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 171, DateTimeKind.Local).AddTicks(7931),
                            UserName = "Jalon_Prohaska"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 189, DateTimeKind.Local).AddTicks(7593),
                            Email = "Kenyon.Adams9@yahoo.com",
                            Password = "7QagstgBaLri8nBd9OAkMn/4Z2JsnV4qmWKI4wuXPVE=",
                            Salt = "iPpx0wJQpyGkkAszAiLbjBEeD6Nvoin8fVbOT3mxi3k=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 189, DateTimeKind.Local).AddTicks(7642),
                            UserName = "Amari_Swaniawski1"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 204, DateTimeKind.Local).AddTicks(8567),
                            Email = "Pietro.Pfeffer37@hotmail.com",
                            Password = "N71JMWv40svAzmNmNYXgtgwoGO5Y0Jvy76H6gz8FxS4=",
                            Salt = "VQiQPwFMUNc8sD+0/pegvafIgQ3lzOo/oC7GIN2I6ys=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 204, DateTimeKind.Local).AddTicks(8616),
                            UserName = "Kenya63"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 222, DateTimeKind.Local).AddTicks(8105),
                            Email = "Georgiana79@yahoo.com",
                            Password = "3hkFCXqAd5BmrqypCollgvA0EO7Oz5SIe0HQX+Q+6sE=",
                            Salt = "hN/QdNuJWkZkNWLZFtqpvzxTSQzqSUbmrJENfYuq9d0=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 222, DateTimeKind.Local).AddTicks(8140),
                            UserName = "Mathias.Jenkins"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 235, DateTimeKind.Local).AddTicks(5967),
                            Email = "Corine_Ernser70@yahoo.com",
                            Password = "/UW94zXMjfJM0/2O+VuJevuFPXBjG5B0v88yEpJiEdc=",
                            Salt = "HnF3irXR8tDY5kJrK268w7LP5o5oD029j8qWAmCf5hc=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 235, DateTimeKind.Local).AddTicks(6007),
                            UserName = "Dorothy96"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 245, DateTimeKind.Local).AddTicks(9891),
                            Email = "Francisca_Herzog@hotmail.com",
                            Password = "yWCidwkWYJoubzObjIkAgT5F4uor5X3lU0rmSJq0k7A=",
                            Salt = "Drp57WQpos5FL2l0ElyKB/9zEWPQ1Ev9kCaox27mW/w=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 245, DateTimeKind.Local).AddTicks(9927),
                            UserName = "Cordie.Corkery93"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 257, DateTimeKind.Local).AddTicks(962),
                            Email = "Vida_Walsh@hotmail.com",
                            Password = "txjde3C3SWo7qcl5VL+F4sGMn30NJUxCvO0ZM5mvYFg=",
                            Salt = "8z/SzfFbKRuNv12iYiJx6qwmUr7BH9IGV/pxaY5NaH4=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 257, DateTimeKind.Local).AddTicks(1002),
                            UserName = "Ramon_Boyle"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 268, DateTimeKind.Local).AddTicks(1518),
                            Email = "Brady_Tromp78@yahoo.com",
                            Password = "akyffyBNY83j/W8nTmrpWBEqYEE4YwvjtNoFE9SDKqA=",
                            Salt = "HCDX0U00laG8jf6OjGl5ciWLQIqoWkeEbLpRw/EHIwY=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 268, DateTimeKind.Local).AddTicks(1553),
                            UserName = "Kayleigh_Romaguera"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 279, DateTimeKind.Local).AddTicks(2967),
                            Email = "Sarah44@gmail.com",
                            Password = "zBMYEoKz/5iBncOgRwEN4PJVE+5ra1qleuVL5CUs9CA=",
                            Salt = "9kth6j8r87I3zVFqW7CqRWN1YbIc4GcgeZWT+r24swY=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 279, DateTimeKind.Local).AddTicks(3002),
                            UserName = "Zoie_Fay"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 289, DateTimeKind.Local).AddTicks(6234),
                            Email = "Lexie55@gmail.com",
                            Password = "JPrFsEuO7DTFUMRnP/b1ghTtczc0gS7dg/XoDeXsVsE=",
                            Salt = "ufR1slDJyOHXQdC87oBOM3gxSh9Gsi+/Zs2AXUrooyY=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 289, DateTimeKind.Local).AddTicks(6261),
                            UserName = "Dax.Koch4"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 299, DateTimeKind.Local).AddTicks(9989),
                            Email = "Pansy.Stroman40@yahoo.com",
                            Password = "PbY7tjchzTtoT7dUVh68DgtpVZLw1M9pqWgHy2JPy5I=",
                            Salt = "k6j0OhvwQqLE+vq53sBrVvP2E4Y3W5ftabxr7OyKsf0=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 300, DateTimeKind.Local).AddTicks(25),
                            UserName = "Jerald_Ullrich"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 310, DateTimeKind.Local).AddTicks(5434),
                            Email = "Katarina.Harvey91@yahoo.com",
                            Password = "ex0f1xsRPvdoUapTBcXrdDaznz+eHElYES+rmFrpQHk=",
                            Salt = "L+jYFQeposS9vgxhruiSqIzdNDHkYDT3Tm8N+L3oKeg=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 310, DateTimeKind.Local).AddTicks(5470),
                            UserName = "Pink.Bartoletti"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 320, DateTimeKind.Local).AddTicks(6434),
                            Email = "Garrison_Gutkowski@gmail.com",
                            Password = "k02qcQYNMIZn+nnGgEqmNy70UMBJFQipuzjN8Inb/j4=",
                            Salt = "isu7YmY2oTeB3Xs8GGoTI9a4wazb3gEVefO/u8kU75Y=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 320, DateTimeKind.Local).AddTicks(6452),
                            UserName = "Garrick60"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 330, DateTimeKind.Local).AddTicks(8447),
                            Email = "Dayna.Littel0@yahoo.com",
                            Password = "kcRfWwp+hIGxz0USVmZmoTxfdkxAotosGCuT2NOBlPE=",
                            Salt = "NTCelS1VZpJ/Ca7ex73p/75UUFBIX5L5zdnBtK91urU=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 330, DateTimeKind.Local).AddTicks(8474),
                            UserName = "Adolph.Oberbrunner21"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 340, DateTimeKind.Local).AddTicks(9181),
                            Email = "Earnest.Leffler@yahoo.com",
                            Password = "BujIDR7vP9qLBP89kh0VkJwSjND061zRkjiJYwHAsAE=",
                            Salt = "atVLAClbpmnL6XtdaYs4WVTMbLgEKMNxkOo1htFpBeA=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 340, DateTimeKind.Local).AddTicks(9198),
                            UserName = "Danyka_Green51"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 351, DateTimeKind.Local).AddTicks(1470),
                            Email = "test@gmail.com",
                            Password = "8Qf0gaPQAbvgRwjcEqu8epTOtlZ0eitQC90+PJVxBpQ=",
                            Salt = "Y19vu0hxvQBfQWMiJn5/6c4q5UwubPqL75Epiw1Quzg=",
                            UpdatedAt = new DateTime(2019, 6, 18, 1, 34, 0, 351, DateTimeKind.Local).AddTicks(1470),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisCommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("DisReactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.DisPostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("DisReactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
